/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbholserviceRouteImport } from './routes/abholservice'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as BarrierefreiheitRouteImport } from './routes/barrierefreiheit'
import { Route as DankeRouteImport } from './routes/danke'
import { Route as DatenloeschungRouteImport } from './routes/datenloeschung'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as DellenHagelschadenRouteImport } from './routes/dellen-hagelschaden'
import { Route as FahrzeugZustandRouteImport } from './routes/fahrzeug-zustand'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LuxusfahrzeugeRouteImport } from './routes/luxusfahrzeuge'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as QualitaetRouteImport } from './routes/qualitaet'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as AbholserviceIndexRouteImport } from './routes/abholservice.index'
import { Route as AbholserviceCityRouteImport } from './routes/abholservice.$city'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAutomatisierungRouteImport } from './routes/admin.automatisierung'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminDellenRouteImport } from './routes/admin.dellen'
import { Route as AdminEinstellungenRouteImport } from './routes/admin.einstellungen'
import { Route as AdminErpnextRouteImport } from './routes/admin.erpnext'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminGalerieRouteImport } from './routes/admin.galerie'
import { Route as AdminKalenderRouteImport } from './routes/admin.kalender'
import { Route as AdminKundenRouteImport } from './routes/admin.kunden'
import { Route as AdminLeistungenRouteImport } from './routes/admin.leistungen'
import { Route as AdminOdooRouteImport } from './routes/admin.odoo'
import { Route as AdminPosteingangRouteImport } from './routes/admin.posteingang'
import { Route as AdminUnterlagenRouteImport } from './routes/admin.unterlagen'
import { Route as AdminZustandRouteImport } from './routes/admin.zustand'
import { Route as ApiAutomationCronRouteImport } from './routes/api.automation-cron'
import { Route as ApiOperatorRouteImport } from './routes/api.operator'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as LeistungenSlugRouteImport } from './routes/leistungen.$slug'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber.index'
import { Route as RatgeberSlugRouteImport } from './routes/ratgeber.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LeistungenSlugIndexRouteImport } from './routes/leistungen.$slug.index'
import { Route as LeistungenSlugCityRouteImport } from './routes/leistungen.$slug.$city'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbholserviceRoute = AbholserviceRouteImport.update({
  id: '/abholservice',
  path: '/abholservice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as …5300 tokens truncated…ath: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxusfahrzeuge': {
      id: '/luxusfahrzeuge'
      path: '/luxusfahrzeuge'
      fullPath: '/luxusfahrzeuge'
      preLoaderRoute: typeof LuxusfahrzeugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualitaet': {
      id: '/qualitaet'
      path: '/qualitaet'
      fullPath: '/qualitaet'
      preLoaderRoute: typeof QualitaetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abholservice/': {
      id: '/abholservice/'
      path: '/'
      fullPath: '/abholservice/'
      preLoaderRoute: typeof AbholserviceIndexRouteImport
      parentRoute: typeof AbholserviceRoute
    }
    '/abholservice/$city': {
      id: '/abholservice/$city'
      path: '/$city'
      fullPath: '/abholservice/$city'
      preLoaderRoute: typeof AbholserviceCityRouteImport
      parentRoute: typeof AbholserviceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automatisierung': {
      id: '/admin/automatisierung'
      path: '/automatisierung'
      fullPath: '/admin/automatisierung'
      preLoaderRoute: typeof AdminAutomatisierungRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dellen': {
      id: '/admin/dellen'
      path: '/dellen'
      fullPath: '/admin/dellen'
      preLoaderRoute: typeof AdminDellenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/einstellungen': {
      id: '/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminEinstellungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/erpnext': {
      id: '/admin/erpnext'
      path: '/erpnext'
      fullPath: '/admin/erpnext'
      preLoaderRoute: typeof AdminErpnextRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galerie': {
      id: '/admin/galerie'
      path: '/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AdminGalerieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kalender': {
      id: '/admin/kalender'
      path: '/kalender'
      fullPath: '/admin/kalender'
      preLoaderRoute: typeof AdminKalenderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kunden': {
      id: '/admin/kunden'
      path: '/kunden'
      fullPath: '/admin/kunden'
      preLoaderRoute: typeof AdminKundenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leistungen': {
      id: '/admin/leistungen'
      path: '/leistungen'
      fullPath: '/admin/leistungen'
      preLoaderRoute: typeof AdminLeistungenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/odoo': {
      id: '/admin/odoo'
      path: '/odoo'
      fullPath: '/admin/odoo'
      preLoaderRoute: typeof AdminOdooRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posteingang': {
      id: '/admin/posteingang'
      path: '/posteingang'
      fullPath: '/admin/posteingang'
      preLoaderRoute: typeof AdminPosteingangRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unterlagen': {
      id: '/admin/unterlagen'
      path: '/unterlagen'
      fullPath: '/admin/unterlagen'
      preLoaderRoute: typeof AdminUnterlagenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zustand': {
      id: '/admin/zustand'
      path: '/zustand'
      fullPath: '/admin/zustand'
      preLoaderRoute: typeof AdminZustandRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/automation-cron': {
      id: '/api/automation-cron'
      path: '/api/automation-cron'
      fullPath: '/api/automation-cron'
      preLoaderRoute: typeof ApiAutomationCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operator': {
      id: '/api/operator'
      path: '/api/operator'
      fullPath: '/api/operator'
      preLoaderRoute: typeof ApiOperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/leistungen/$slug': {
      id: '/leistungen/$slug'
      path: '/$slug'
      fullPath: '/leistungen/$slug'
      preLoaderRoute: typeof LeistungenSlugRouteImport
      parentRoute: typeof LeistungenRoute
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof RatgeberRoute
    }
    '/ratgeber/$slug': {
      id: '/ratgeber/$slug'
      path: '/$slug'
      fullPath: '/ratgeber/$slug'
      preLoaderRoute: typeof RatgeberSlugRouteImport
      parentRoute: typeof RatgeberRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$slug/': {
      id: '/leistungen/$slug/'
      path: '/'
      fullPath: '/leistungen/$slug/'
      preLoaderRoute: typeof LeistungenSlugIndexRouteImport
      parentRoute: typeof LeistungenSlugRoute
    }
    '/leistungen/$slug/$city': {
      id: '/leistungen/$slug/$city'
      path: '/$city'
      fullPath: '/leistungen/$slug/$city'
      preLoaderRoute: typeof LeistungenSlugCityRouteImport
      parentRoute: typeof LeistungenSlugRoute
    }
  }
}

interface AbholserviceRouteChildren {
  AbholserviceCityRoute: typeof AbholserviceCityRoute
  AbholserviceIndexRoute: typeof AbholserviceIndexRoute
}

const AbholserviceRouteChildren: AbholserviceRouteChildren = {
  AbholserviceCityRoute: AbholserviceCityRoute,
  AbholserviceIndexRoute: AbholserviceIndexRoute,
}

const AbholserviceRouteWithChildren = AbholserviceRoute._addFileChildren(
  AbholserviceRouteChildren,
)

interface AdminRouteChildren {
  AdminAutomatisierungRoute: typeof AdminAutomatisierungRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDellenRoute: typeof AdminDellenRoute
  AdminEinstellungenRoute: typeof AdminEinstellungenRoute
  AdminErpnextRoute: typeof AdminErpnextRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminGalerieRoute: typeof AdminGalerieRoute
  AdminKalenderRoute: typeof AdminKalenderRoute
  AdminKundenRoute: typeof AdminKundenRoute
  AdminLeistungenRoute: typeof AdminLeistungenRoute
  AdminOdooRoute: typeof AdminOdooRoute
  AdminPosteingangRoute: typeof AdminPosteingangRoute
  AdminUnterlagenRoute: typeof AdminUnterlagenRoute
  AdminZustandRoute: typeof AdminZustandRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomatisierungRoute: AdminAutomatisierungRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminDellenRoute: AdminDellenRoute,
  AdminEinstellungenRoute: AdminEinstellungenRoute,
  AdminErpnextRoute: AdminErpnextRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminGalerieRoute: AdminGalerieRoute,
  AdminKalenderRoute: AdminKalenderRoute,
  AdminKundenRoute: AdminKundenRoute,
  AdminLeistungenRoute: AdminLeistungenRoute,
  AdminOdooRoute: AdminOdooRoute,
  AdminPosteingangRoute: AdminPosteingangRoute,
  AdminUnterlagenRoute: AdminUnterlagenRoute,
  AdminZustandRoute: AdminZustandRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LeistungenSlugRouteChildren {
  LeistungenSlugCityRoute: typeof LeistungenSlugCityRoute
  LeistungenSlugIndexRoute: typeof LeistungenSlugIndexRoute
}

const LeistungenSlugRouteChildren: LeistungenSlugRouteChildren = {
  LeistungenSlugCityRoute: LeistungenSlugCityRoute,
  LeistungenSlugIndexRoute: LeistungenSlugIndexRoute,
}

const LeistungenSlugRouteWithChildren = LeistungenSlugRoute._addFileChildren(
  LeistungenSlugRouteChildren,
)

interface LeistungenRouteChildren {
  LeistungenSlugRoute: typeof LeistungenSlugRouteWithChildren
  LeistungenIndexRoute: typeof LeistungenIndexRoute
}

const LeistungenRouteChildren: LeistungenRouteChildren = {
  LeistungenSlugRoute: LeistungenSlugRouteWithChildren,
  LeistungenIndexRoute: LeistungenIndexRoute,
}

const LeistungenRouteWithChildren = LeistungenRoute._addFileChildren(
  LeistungenRouteChildren,
)

interface RatgeberRouteChildren {
  RatgeberSlugRoute: typeof RatgeberSlugRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
}

const RatgeberRouteChildren: RatgeberRouteChildren = {
  RatgeberSlugRoute: RatgeberSlugRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
}

const RatgeberRouteWithChildren = RatgeberRoute._addFileChildren(
  RatgeberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbholserviceRoute: AbholserviceRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AgbRoute: AgbRoute,
  B2bRoute: B2bRoute,
  BarrierefreiheitRoute: BarrierefreiheitRoute,
  DankeRoute: DankeRoute,
  DatenloeschungRoute: DatenloeschungRoute,
  DatenschutzRoute: DatenschutzRoute,
  DellenHagelschadenRoute: DellenHagelschadenRoute,
  FahrzeugZustandRoute: FahrzeugZustandRoute,
  FaqRoute: FaqRoute,
  GalerieRoute: GalerieRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  LeistungenRoute: LeistungenRouteWithChildren,
  LoginRoute: LoginRoute,
  LuxusfahrzeugeRoute: LuxusfahrzeugeRoute,
  PreiseRoute: PreiseRoute,
  QualitaetRoute: QualitaetRoute,
  RatgeberRoute: RatgeberRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WiderrufRoute: WiderrufRoute,
  ApiAutomationCronRoute: ApiAutomationCronRoute,
  ApiOperatorRoute: ApiOperatorRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
