/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as QualitaetRouteImport } from './routes/qualitaet'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AbholserviceIndexRouteImport } from './routes/abholservice.index'
import { Route as AbholserviceCityRouteImport } from './routes/abholservice.$city'
import { Route as LeistungenIndexRouteImport } from './routes/leistungen.index'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as KalenderTokenIcsRouteImport } from './routes/kalender.$token.ics'
import { Route as LeistungenServiceIndexRouteImport } from './routes/leistungen.$service.index'
import { Route as LeistungenServiceCityRouteImport } from './routes/leistungen.$service.$city'
import { Route as AuthenticatedAdminAdminKundenRouteImport } from './routes/_authenticated/_admin/admin.kunden'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const QualitaetRoute = QualitaetRouteImport.update({
  id: '/qualitaet',
  path: '/qualitaet',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AbholserviceIndexRoute = AbholserviceIndexRouteImport.update({
  id: '/abholservice/',
  path: '/abholservice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbholserviceCityRoute = AbholserviceCityRouteImport.update({
  id: '/abholservice/$city',
  path: '/abholservice/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenIndexRoute = LeistungenIndexRouteImport.update({
  id: '/leistungen/',
  path: '/leistungen/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const KalenderTokenIcsRoute = KalenderTokenIcsRouteImport.update({
  id: '/kalender/$token/ics',
  path: '/kalender/$token/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenServiceIndexRoute = LeistungenServiceIndexRouteImport.update({
  id: '/leistungen/$service/',
  path: '/leistungen/$service/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenServiceCityRoute = LeistungenServiceCityRouteImport.update({
  id: '/leistungen/$service/$city',
  path: '/leistungen/$service/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminKundenRoute =
  AuthenticatedAdminAdminKundenRouteImport.update({
    id: '/kunden',
    path: '/kunden',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/preise': typeof PreiseRoute
  '/qualitaet': typeof QualitaetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/abholservice/$city': typeof AbholserviceCityRoute
  '/abholservice/': typeof AbholserviceIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/kalender/$token/ics': typeof KalenderTokenIcsRoute
  '/leistungen/$service/$city': typeof LeistungenServiceCityRoute
  '/leistungen/$service/': typeof LeistungenServiceIndexRoute
  '/admin/kunden': typeof AuthenticatedAdminAdminKundenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/preise': typeof PreiseRoute
  '/qualitaet': typeof QualitaetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/abholservice/$city': typeof AbholserviceCityRoute
  '/abholservice': typeof AbholserviceIndexRoute
  '/leistungen': typeof LeistungenIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/kalender/$token/ics': typeof KalenderTokenIcsRoute
  '/leistungen/$service/$city': typeof LeistungenServiceCityRoute
  '/leistungen/$service': typeof LeistungenServiceIndexRoute
  '/admin/kunden': typeof AuthenticatedAdminAdminKundenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/preise': typeof PreiseRoute
  '/qualitaet': typeof QualitaetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/abholservice/$city': typeof AbholserviceCityRoute
  '/abholservice/': typeof AbholserviceIndexRoute
  '/leistungen/': typeof LeistungenIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/kalender/$token/ics': typeof KalenderTokenIcsRoute
  '/leistungen/$service/$city': typeof LeistungenServiceCityRoute
  '/leistungen/$service/': typeof LeistungenServiceIndexRoute
  '/_authenticated/_admin/admin/kunden': typeof AuthenticatedAdminAdminKundenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/preise'
    | '/qualitaet'
    | '/reset-password'
    | '/sitemap.xml'
    | '/abholservice/$city'
    | '/abholservice/'
    | '/leistungen/'
    | '/admin'
    | '/kalender/$token/ics'
    | '/leistungen/$service/$city'
    | '/leistungen/$service/'
    | '/admin/kunden'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/preise'
    | '/qualitaet'
    | '/reset-password'
    | '/sitemap.xml'
    | '/abholservice/$city'
    | '/abholservice'
    | '/leistungen'
    | '/admin'
    | '/kalender/$token/ics'
    | '/leistungen/$service/$city'
    | '/leistungen/$service'
    | '/admin/kunden'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/datenschutz'
    | '/impressum'
    | '/preise'
    | '/qualitaet'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/_admin'
    | '/abholservice/$city'
    | '/abholservice/'
    | '/leistungen/'
    | '/_authenticated/_admin/admin'
    | '/kalender/$token/ics'
    | '/leistungen/$service/$city'
    | '/leistungen/$service/'
    | '/_authenticated/_admin/admin/kunden'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  PreiseRoute: typeof PreiseRoute
  QualitaetRoute: typeof QualitaetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AbholserviceCityRoute: typeof AbholserviceCityRoute
  AbholserviceIndexRoute: typeof AbholserviceIndexRoute
  LeistungenIndexRoute: typeof LeistungenIndexRoute
  KalenderTokenIcsRoute: typeof KalenderTokenIcsRoute
  LeistungenServiceCityRoute: typeof LeistungenServiceCityRoute
  LeistungenServiceIndexRoute: typeof LeistungenServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualitaet': {
      id: '/qualitaet'
      path: '/qualitaet'
      fullPath: '/qualitaet'
      preLoaderRoute: typeof QualitaetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/abholservice/': {
      id: '/abholservice/'
      path: '/abholservice'
      fullPath: '/abholservice/'
      preLoaderRoute: typeof AbholserviceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abholservice/$city': {
      id: '/abholservice/$city'
      path: '/abholservice/$city'
      fullPath: '/abholservice/$city'
      preLoaderRoute: typeof AbholserviceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/': {
      id: '/leistungen/'
      path: '/leistungen'
      fullPath: '/leistungen/'
      preLoaderRoute: typeof LeistungenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/kalender/$token/ics': {
      id: '/kalender/$token/ics'
      path: '/kalender/$token/ics'
      fullPath: '/kalender/$token/ics'
      preLoaderRoute: typeof KalenderTokenIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$service/': {
      id: '/leistungen/$service/'
      path: '/leistungen/$service'
      fullPath: '/leistungen/$service/'
      preLoaderRoute: typeof LeistungenServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen/$service/$city': {
      id: '/leistungen/$service/$city'
      path: '/leistungen/$service/$city'
      fullPath: '/leistungen/$service/$city'
      preLoaderRoute: typeof LeistungenServiceCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/kunden': {
      id: '/_authenticated/_admin/admin/kunden'
      path: '/kunden'
      fullPath: '/admin/kunden'
      preLoaderRoute: typeof AuthenticatedAdminAdminKundenRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminKundenRoute: typeof AuthenticatedAdminAdminKundenRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminKundenRoute: AuthenticatedAdminAdminKundenRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  PreiseRoute: PreiseRoute,
  QualitaetRoute: QualitaetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AbholserviceCityRoute: AbholserviceCityRoute,
  AbholserviceIndexRoute: AbholserviceIndexRoute,
  LeistungenIndexRoute: LeistungenIndexRoute,
  KalenderTokenIcsRoute: KalenderTokenIcsRoute,
  LeistungenServiceCityRoute: LeistungenServiceCityRoute,
  LeistungenServiceIndexRoute: LeistungenServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
